# Generated by Django 4.2.4 on 2023-08-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iin',
            field=models.CharField(max_length=20),
        ),
    ]
