# Generated by Django 4.2.4 on 2023-08-21 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0003_alter_inventory_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iin',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
